"""empty message

Revision ID: 9fd59dd49419
Revises: 2ec4895d5fd0
Create Date: 2023-01-30 16:51:03.948476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd59dd49419'
down_revision = '2ec4895d5fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'link_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('link_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
