"""empty message

Revision ID: 16a3426149b5
Revises: 9fd59dd49419
Create Date: 2023-02-02 17:59:37.157185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a3426149b5'
down_revision = '9fd59dd49419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'subranddit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.alter_column('posts', 'subranddit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
